### ISSUE TITLE
Could we use four-color theorem to color variations differently so they are more readable?

### ISSUE THREAD

**Issue by Siderite** [Siderite/lichessTools#180]
If we look at the move list as a map, then variations could be differentiated with just four colors.

**Comment by Siderite** [comment]
Added the Move colorize theme that highlights the various levels.

**Comment by Dboingue** [comment]
The 4 color theorem from graph theory, it is also the traveling salesman problem.  The best path that does not revisit any cities.  I might remember the correspondance wrong.  It is about adjacency.  But I get the chess thinking point to be about having more redundant visual signal in peripheral vision if using the move list as a map of the decision subtree having been explored.

I am curious about the imagination behind associating that to the country planar "tesselation" (my natural english is lacking vocabulary, I might be borrowing from more specialized english I know, and here it is how to put a planar graph on space.. like in finite element methods. but tesselation I think itself a pattern of meshing.  anyway..  the country adjacency and connectivity problem..  Is it about 2D space and some assumption on the shapes of such simply connected sets on the plane.  I am not being precise. working from old memory, and guessing too.  It says that 4 color is enough to distinguish all countries from each other everywhere, right?   So the move list being at most spatially complex a planar graph with no cycles.. hmm..  maybe we do need the travelling problem tranformation of the country adjacency..    The shape assumption being that we can assimilate each country to a node and all its adjacent countries border as link of that graphs.  I think my pet subject might be warranted here.

The lichess move list is not that planar graph. It would be if we were having dotted transversal lines in the vertical direction linking distinct move-tree nodes as being the same actual position. 

However, the issue here being about distinguishing a maximum of branches from each other as some peripheral visions map while still having best retina real estate on the board (by peripheral, I could extend to micro-gaze eye movements to make sure, time is involved here, but small durations, we do lots of stuff with our eyes that we often don't even know about).

I think you are onto somthing though about the theorem calling out.. Indicative I would suggest that you share the same need to see where the positions are, that are represented by the node in that decision tree, sometimes being the same position represented 2 times in different branches of that tree.   I hope I am not adding confusion. or that if so, it is only temporary passage.

For the givens from lichess (and any other chess software using move minimal change information based on implicit position being the thing being changed, and only considering node view need not whole set of positions visited, the construction only visible one node at a time, and no human memory across branches).

You could have 2 alternating colors if only to differentiates pair of sibling subtrees (better be general, we have nested sub-trees, but at each branching point at least for the next node we do have branches, again local view, construction view).

but there could be a need for identificatoin as map of the bushiness going to as many colors as the human mind can in real times compare respective positions in visual working memory for move selection or decision while in variation exploration, or assessment of future positions to plan as targets.

that was brainstorming. maybe also not appropriate. let me know. deletable and movable. with suggestion and help. thanks for the stimulating issue titling.. and this entreprising visual lichess "chantier de construction".    It hits many spots.  I have almost 5 years almost daily experience using lichess, with lots of analysis and study emphasis.

**Comment by Siderite** [comment]
I was trying to limit the colors I would be using, so that they are clearly defined and can be customized by the user, for example. But I've abandoned the idea because a PGN was not a map and determining adjacency was not so easy (considering one might also resize the page and change things). 

In the end I've added the new theme which is pretty gaudy :) but differentiates the variations up to the 7th level or something.
