### ISSUE TITLE
Advanced feature: PGN editor

### ISSUE THREAD

**Issue by Siderite** [Siderite/lichessTools#210]
A lot of the features that I occasionally wanted for PGN editing (normalization, pruning, automatic evaluation, undo/redo chain, copy/paste, etc.) are more inline with a PGN editor than with board analysis. 

This feature would allow people to use very advanced and specific tools to edit and reformat their PGNs. It would have to be some sort of profound rearranging of the Analysis page, or even the Study one or perhaps a completely new thing, like Preferences. A popup covering the entire screen could work as well.

Anyway, complex tool, a lot of work, probably needing multiple tools working together.

**Comment by Siderite** [comment]
Extra functionality: graphical representation of the PGN (graph, with some js library)

**Comment by Dboingue** [comment]
js wrapper of graph related libraries I would suggest.
keywords to make precise when more time/energy (limited resource for me, a lump).
graphviz (just graph viz), neo4j (database AND graph viz), banskguia GUI author repo on only non-chess software marriage promising database format, maintream database software compatible.. find links).

this is WIP suggestions.  somewhere else but in this repo there is a reference to chess tree.  put linkk to that here too. As it is close to tree as graph.   

I would also suggest making clear what graph in relation to chess notions.  A graph can be many things..
Chess trees ubuitously  are about single material unit change of board coordinates, often pointed as a "moves".  The typical compact notation assuming other chess information given somewhere but not in the notation, trees of SAN notation such hand-moves ply per ply. The ply chess time unit being the only meaning of the links between the nodes which as only described as hand-moves.  There are 20 trees of such legal hand moves necessary to describe all of chess games.  those are assuming a root POSITION to be made real chess games. then one can construct the actual grame by applying the trees node after node (one can't skip a node, one has to keep applying and traverse, likely depth first but mostly sequentially).

To obtain all the games that all the paths in such undirected graph (being trees, the direction is implied, lots of stuff implied).

Now, computers love to save space because they have no brain blood flood based resource limitations.  We like to keep our work cognitively unloaded somewhere so we can use our whole parallel brain advantage on seeing the whole.

How are we going to describe that constructible by undertimed 20 trees applicatnoi to the standard initial positoin (or subtrree for any other root position, PGN would have to give such root position with the partial subtree recipe to get the real stuff some day, or in lichess board expansions, also keeping that napking tree shadow representation, since we have the boards on the left or above it.

Well.  pregnancy ending:  another graph is going to be needed..  a graph of the unique legal positions that all those 20 trees hint at, and could construct if tree applied to their sometimes made explicit root positoin.

I may have to excise, some bonus winks and change language above to look more legit..

**Comment by Dboingue** [comment]
please feedback on my verbosity. priority to being understood.. of course..

**Comment by Siderite** [comment]
PGN Editor implemented in v2.3.2. More features to come.

**Comment by Siderite** [comment]
PGN Editor is pretty much done. Extra features will be added in separate issues.
