### ISSUE TITLE
Can't  install and update

### ISSUE THREAD

**Issue by SergioGlorias** [Siderite/lichessTools#244]
Chromium and Vivaldi not install

![imagem](https://github.com/Siderite/lichessTools/assets/9739913/43c0fef2-7c65-41d1-bcb7-90ff1158ea0e)

**Comment by Siderite** [comment]
I believe this is a limitation of the browser you are trying to use. The mechanism that loads the scripts is specific to Manifest V3, in the Chromium implementation. Firefox, for example, does not support it. I imagine these browsers have the same issue.

If you want a mobile browser that accepts extensions, try Kiwi.

**Comment by SergioGlorias** [comment]
> I believe this is a limitation of the browser you are trying to use. The mechanism that loads the scripts is specific to Manifest V3, in the Chromium implementation. Firefox, for example, does not support it. I imagine these browsers have the same issue.
> 
> If you want a mobile browser that accepts extensions, try Kiwi.

Vivaldi, Chromium after tested Google Chrome:  same problem

Firefox: chrome store not work

**Comment by SergioGlorias** [comment]
Chromium: `v117`
Vivaldi: `Chromium v116`
Chrome: `117`

can't install extension

"tools/exportPGN/tool.js" can't loader

**Comment by Siderite** [comment]
I use Brave, but I also tried Chrome right now:
![image](https://github.com/Siderite/lichessTools/assets/260529/7dc573fb-a4b1-4f11-a771-d8725db0bdaa)
Also Edge:
![image](https://github.com/Siderite/lichessTools/assets/260529/cf18186b-e331-4cb7-8766-6167ef6bb68f)

I don't know what the issue is. Maybe a conflict with another extension?
If you see an error related to tools/exportPGN, then the extension is installed, only it throws some error.

Can you paste here the console output?

**Comment by Siderite** [comment]
Ah! I may know what's going on. You use it on Linux, right? It was a difference in casing. Fixing it now.

**Comment by Siderite** [comment]
fixed (hopefully) in v2.1.24
