### ISSUE TITLE
Spaced repetition SR wants to play non existing lines

### ISSUE THREAD

**Issue by derpafist** [Siderite/lichessTools#883]
There are several problems here.
When I play a wrong move in the preview while rec is off, that move is added to the pgn. Intended?
When I then play another preview, these new lines are played, even though they have not been recorded.
So I closed the preview and enabled rec s.t. the wrong lines are removed.
The big issue is now that when I replay, SR still wants to play the removed lines but this failes and the lesson ends with the success screen without finishing the non existing line. But this leads to a loop: SR wants to play the same line over and over and never goes to another because it can't finish what it wants to play.

**Comment by Siderite** [comment]
The REC off issue is real. I have no way to determine which moves are "real" and which not, because Lichess changed the way it marked those and when you make a move, it's sent to the server and then a reply comes back and updates the move list.

The most I can do is probably not allow extended interactive when REC is off.

And yes, I haven't thought of that. I have to check that the "correct" line also exists. That's an ugly bug.

**Comment by Siderite** [comment]
Fixed, I hope, in v2.3.162

**Comment by derpafist** [comment]
You are a hero! And a very fast one!

**Comment by derpafist** [comment]
Still, non existing lines are attempted.
I played a line but forgot that rec was on. Then it was played in the following lession. I closed it by hitting preview and deleted the line. But even after a refresh it only wants to play that line and fails.
